/*
 * dual_spi_adc.h
 *
 *  Created on: Feb 25, 2025
 *      Author: ogahe
 */

#ifndef INC_DUAL_SPI_ADC_H_
#define INC_DUAL_SPI_ADC_H_

#include "main.h"

// Extern declarations for SPI handles (generated by CubeMX)
extern SPI_HandleTypeDef hspi2; // For channel 1 (e.g., M0)
extern SPI_HandleTypeDef hspi3; // For channel 2 (e.g., M1)

// Define the common NSS GPIO pin for the ADC
#define ADC_NSS_GPIO_Port   GPIOB
//#define ADC_NSS_Pin           // Adjust to your configuration

// Function prototypes
void DualSPI_ADC_Read(uint16_t *adc_ch1, uint16_t *adc_ch2);

#endif /* INC_DUAL_SPI_ADC_H_ */
